class PromptBuilder:
    def __init__(self, question, mode):
        """
        初始化 PromptBuilder 实例

        Args:
        - question (str): 输入的问题
        - mode (str): 模式，可选值为 question_decompose, filter_triples, filter_entities,
                      structral_enrich, feature_enrich, qa
        """
        self.question = question
        self.mode = mode

        # 根据 mode 初始化各个部分内容
        self.role = self.get_role()
        self.instruction = self.get_instruction()
        self.demonstrations = self.get_demonstrations()

        # 组装 prompt
        self.result_prompt = self.build_prompt()

    def get_role(self):
        """
        获取 role 部分的内容（<<SYS>><</SYS>> 中的描述）。
        根据 mode 不同，返回不同的角色信息。
        """
        role_dict = {
            'question_decompose': "",
            'triples_trans': "",
            'filter_triples': "",
            'filter_entities': "",
            'structral_enrich': (
                "You are a linguist capable of understanding user queries and the semantic information "
                "contained in triples. You can enhance the semantic information of triples based on the principles of similarity, "
                "symmetry, and transitivity, bridging the semantic gap between the triples and the user queries. Your goal is to "
                "augment the triples semantically so they can better address the user’s queries."
            ),
            'feature_enrich': (
                "You are a linguist with extensive expertise in ontology knowledge. You have the ability to "
                "understand the context of entities, including user queries and the semantic information of triples. Based on "
                "the contextual information of an entity, you can accurately and appropriately add ontologies to the entity. "
                "Your goal is to bridge the semantic gap between entities and user queries by adding relevant ontologies, "
                "thereby semantically augmenting the entities to enable them to better address the user's queries."
            ),
            'qa': "",
            'direct_qa': ""
        }
        return role_dict.get(self.mode, "You are a helpful assistant.")

    def get_instruction(self):
        """
        获取 instruction 部分的内容。
        根据 mode 不同，返回不同的指令信息。
        """
        instruction_dict = {
            'question_decompose': (
                "Given a question, decompose it step by step into smaller components until it is broken down into unit queries "
                "that can be directly answered without further reasoning or decomposition. If a question can still be further broken down, it must be divided into at least two or more sub-questions."
                "Otherwise, the question is considered a unit query. If the given question is already a unit query, no decomposition "
                "is needed. Your output should only include the tree structure of the "
                "decomposed question, with sub-questions indented using '-', and no additional content should be provided, just the tree structure. "
                "The format for the decomposition tree is as follows:\n"
                "### decomposition tree format ###\n"
                "question\n"
                "-sub-question\n"
                "--sub-sub-question\n"
                "---sub-sub-sub-question\n"
                "---sub-sub-sub-question\n"
                "--sub-sub-question\n"
                "-sub-question\n"
                "### decomposition tree format ###\n"
                "I will provide examples, please complete your task after reviewing them."
            ),
            'triples_trans': (
                "Given some triples from a knowledge graph, please convert each one into a natural language question. "
                "The triple query is formatted as (h, r, ?) and (?, r, t), where 'h' represents the head entity and 'r' "
                "represents the relation and 't' represents the tail entity. The purpose of the query is to identify the set of tail or head entities "
                "connected to 'h' or 't' through the relation 'r'. Your task is to transform this query into a question "
                "in natural language form. I will provide you with examples, please complete your task after reviewing them."
            ),
            'filter_triples': (
                "Given a set of user unit queries, triples, and their corresponding triple unit queries "
                "(format: triple-triple unit query), your task is to identify the related subgraph of triple unit queries "
                "for each user unit query and return the triples corresponding to those triple unit queries. A user unit query "
                "may be associated with multiple triple unit queries or none at all. For each user unit query, find the "
                "relevant triples and output them in the format: user unit query-triple. If multiple triple unit queries are "
                "related, output in the format: user unit query-triple1-triple2-triple3-..., and if no related triple unit "
                "queries exist, output: user unit query-None. I will provide you with examples, please complete your task "
                "after reviewing them."
            ),
            'filter_entities': "",
            'structral_enrich': (
                "You are given a subgraph that consists of multiple triples, where each triple corresponds to one or more user queries.\n"
                "The format is as follows:\n"
                "triple(entity1, relation, entity2) - query1 - query2 - query3 - ...\n"
                "Here, a query represents a question from the user. The triple associated with a query may contain information relevant to answering the question.\n"
                "However, the semantic connections both within and between triples are typically weak, lacking dense links to clearly establish relationships between entities.\n"
                "As a result, answers to the queries are often implicit and require complex reasoning.\n"
                "To bridge the semantic gap between the queries and the triples, please perform semantic enhancement on the subgraph by considering the user queries.\n"
                "Specifically, you will utilize the following properties for semantic enhancement: Similarity, Symmetry, and Transitivity.\n"
                "Below, you will find detailed explanations of these properties along with examples. Please keep these principles in mind as you perform semantic enhancement.\n"
                "{Similarity}\n"
                "The property of similarity indicates that for a given triple (e1, r1, e2), we can find an alternative relationship r2 that is semantically different from r1\n"
                "but shares the same directional connection between e1 and e2. In other words, the entities e1 and e2 remain connected in the same direction,\n"
                "but the meaning of the connection changes to reflect the semantics of r2. For example:\n"
                "If (e1, r1, e2) exists, then (e1, r2, e2) may also exist, where r1 ≠ r2, and r1 and r2 represent different relationships.\n"
                "{/Similarity}\n"
                "{Symmetry}\n"
                "The property of symmetry indicates that for a given triple (e1, r1, e2), there exists a new relationship r2 that is semantically different from r1\n"
                "and reverses the direction of the connection between e1 and e2. In other words, the new triple swaps the roles of e1 and e2 while preserving\n"
                "their semantic relationship in a reversed form. For example:\n"
                "If (e1, r1, e2) exists, then (e2, r2, e1) may also exist, where r1 ≠ r2, and r1 and r2 represent different relationships.\n"
                "{/Symmetry}\n"
                "{Transitivity}\n"
                "The property of transitivity indicates that when two triples share a common entity, we can combine their relationships into a new relationship\n"
                "that connects the remaining two entities directly. Specifically, if (e1, r1, e2) and (e2, r2, e3) exist, then there exists a new relationship r3\n"
                "that semantically encompasses both r1 and r2, forming a new triple (e1, r3, e3). The new relationship r3 captures the combined semantics of r1 and r2.\n"
                "For example:\n"
                "Given (e1, r1, e2) and (e2, r2, e3), we derive (e1, r3, e3), where r3 combines the meanings of r1 and r2.\n"
                "{/Transitivity}\n"
                "{Procedure}\n"
                "Step 1:\n"
                "Examine the given triples and their associated queries. Understand the information contained within the triples and the questions being asked in the queries.\n"
                "Step 2:\n"
                "Using the similarity and symmetry properties, perform semantic enhancement on the given 1-hop subgraph (i.e., triples where connections involve only directly linked entities).\n"
                "Step 3:\n"
                "Using the transitivity property, perform semantic enhancement on the given multi-hop subgraph (i.e., triples where connections involve intermediary entities).\n"
                "Step 4:\n"
                "Output the newly generated triples resulting from the semantic enhancement process.\n"
                "{/Procedure}\n"
                "I will provide examples, please complete your task after reviewing them."
            ),
            'feature_enrich': (
                "You are provided with an entity list. Each entity in the list is accompanied by its context information, which consists of two parts:\n"
                "1. Relevant triples associated with the entity.\n"
                "2. Relevant user queries associated with the entity.\n"
                "The context format for each entity is as follows:\n"
                "[$entity$ context]\n"
                "relavent triple(s):triple1-triple2-triple3-...\n"
                "relavent user query(ies):query1-query2-query3-...\n"
                "[/$entity$ context]\n"
                "Your task is to analyze the context information of each entity, apply your expert knowledge, and assign an appropriate ontology to the entity.\n"
                "The added ontology should:\n"
                "1. Be semantically consistent with the entity's context information.\n"
                "2. Avoid any contradictions or irrelevance with the given context.\n"
                "3. Enhance the entity's ability to better answer the user query(ies) in its context.\n"
                "Store the ontology assignments in a set called {result}. The {result} set is initially empty. Each ontology assignment should follow the format:\n"
                "{result}\n"
                "(entity,ontology_relation,newly added ontology)\n"
                "...\n"
                "{/result}\n"
                "You must choose an appropriate ontology relation from the options provided below.\n"
                "{ontology relation definition}\n"
                "HYP: Hypernym relation\n"
                "Refers to the relation where a broader or more general concept includes or encompasses a more specific or specialized concept.\n"
                "Hypernym_isA\n"
                "Is a type of...\n"
                "Hypernym_locateAt\n"
                "Is located at...\n"
                "Hypernym_mannerOf\n"
                "A is a specific implementation or way of B. Similar to \"isA,\" but used for verbs. For example, \"auction\" -> \"sale\".\n"
                "IND: Induction relation\n"
                "Refers to the relation between individual entities and conceptual generalizations derived from a class of entities with common characteristics.\n"
                "Induction_belongTo\n"
                "This relation is commonly used in SPG to describe the classification relation from entity types to concept types. For example, \"company event\" -> \"company event category\".\n"
                "INC: Inclusion relation\n"
                "Expresses the relation between parts and the whole.\n"
                "Inclusion_isPartOf\n"
                "A is a part of B.\n"
                "Inclusion_madeOf\n"
                "A is made up of B. For example, \"bottle\" -> \"plastic\".\n"
                "Inclusion_derivedFrom\n"
                "A is derived from or originated from B, used to express composite concepts.\n"
                "Inclusion_hasContext\n"
                "A is a word used in the context of B, where B can be a subject area, technical field, or regional dialect. For example, \"astern\" -> \"ship\".\n"
                "{/ontology relation definition}\n"
                "You can only choose an appropriate {ontology_relation} from {Hypernym_isA, Hypernym_locateAt, Hypernym_mannerOf, Induction_belongTo, Inclusion_isPartOf, Inclusion_madeOf, Inclusion_derivedFrom, Inclusion_hasContext}.\n"
                "Your task will follow the four steps below:\n"
                "{Procedure}\n"
                "Step 1:\n"
                "For the first $entity$ in the entity list, read its context information carefully. Based on the provided context and your expert knowledge, answer the following question:\n"
                "Does this $entity$ already have an ontology assigned?\n"
                "If yes, proceed to Step 2.\n"
                "If no, move to Step 3.\n"
                "Step 2:\n"
                "Using the entity's context information and your expert knowledge:\n" 
                "Identify a list of appropriate ontologies for the entity.\n"  
                "For each ontology in this list, select the most suitable ontology relation from the {ontology_relation} options.\n"
                "Format each assignment as (entity, ontology_relation, newly added ontology) and add it to the {result} set.\n"
                "Remove this $entity$ and its corresponding context information from the entity list.\n"
                "Output the current {result} set in the following format:\n"
                "{result}\n"
                "...\n"
                "{/result}\n"
                "Then move to Step 3.\n"
                "Step 3:\n"
                "Check if the entity list is now empty:\n"
                "If the list is empty, proceed to Step 4.\n"
                "If the list is not empty, return to Step 1 and repeat the process for the next $entity$.\n"
                "Step 4:\n"
                "Once all entities have been processed, output the final {result} set containing all (entity, ontology_relation, newly added ontology) assignments in the following format:\n"
                "{result}\n"
                "(entity,ontology_relation,newly added ontology)\n"
                "...\n"
                "{/result}\n"
                "{/Procedure}\n"
                "I will provide examples, please complete your task after reviewing them.\n"
            ),
            'qa': (
                "You are given an input question along with additional information to assist in answering the question. The additional information includes a set of relevant triples and sub-questions corresponding to each triple. The format of a triple is as follows:\n"
                "(e1, r, e2)\n"
                "Your task is to perform step-by-step reasoning based on the provided additional information to arrive at the answer. You should output your process of thinking and reasoning then the final answer. If there is only one answer, directly output that answer. If there are multiple answers, separate them using commas.\n"
                "Input Format:\n"
                "Input:\n"
                "question:\n"
                "{input question}\n"
                "information:\n"
                "{triple1-sub query1.1-sub query1.2-sub query1.3-...}\n"
                "{triple2-sub query2.1-sub query2.2-sub query2.3-...}\n"
                "Output Format:\n"
                "Output:\n"
                "{thoughts & reason}\n"
                "Your process of thinking and reasoning\n"
                "...\n"
                "{/thoughts & reason}\n"
                "Final answer:\n"
                "{answer}"
            ),
            'direct_qa': (
                "You are given an input question along with additional information to assist in answering the question. The additional information includes a set of relevant triples. The format of a triple is as follows:\n"
                "(e1, r, e2)\n"
                "Your task is to perform step-by-step reasoning based on the provided additional information to arrive at the answer. You should output your process of thinking and reasoning then the final answer. If there is only one answer, directly output that answer. If there are multiple answers, separate them using commas.\n"
                "Input Format:\n"
                "Input:\n"
                "question:\n"
                "{input question}\n"
                "information:\n"
                "{triple1}\n"
                "{triple2}\n"
                "{triple3}\n"
                "...\n"
                "Output Format:\n"
                "Output:\n"
                "{thoughts & reason}\n"
                "Your process of thinking and reasoning\n"
                "...\n"
                "{/thoughts & reason}\n"
                "Final answer:\n"
                "{answer}"
            )
        }
        return instruction_dict.get(self.mode, "Perform the requested task based on the mode.")

    def get_demonstrations(self):
        """
        获取 demonstrations 部分的内容。
        根据 mode 不同，可以返回一系列任务相关的例子。
        支持多个 example 的动态组装。
        """
        # 定义每种模式的示例
        demonstrations_dict = {
            'question_decompose': {
                1: (
                    "input: What is the name of the scientist who developed the theory that explains why objects fall to Earth?\n"
                    "output:\n"
                    "What is the name of the scientist who developed the theory that explains why objects fall to Earth?\n"
                    "-What is the theory that explains why objects fall to Earth?\n"
                    "--Is there a theory for why objects fall to Earth?\n"
                    "--What is the name of this theory?\n"
                    "-Who developed this theory?\n"
                    "--Is this theory associated with a specific scientist?\n"
                    "--What is the name of this scientist?"
                ),
                2: (
                    "input: What type of energy powers the device invented by Thomas Edison that produces light?\n"
                    "output:\n"
                    "What type of energy powers the device invented by Thomas Edison that produces light?\n"
                    "-What device produces light and was invented by Thomas Edison?\n"
                    "--Who is Thomas Edison?\n"
                    "--What devices did Thomas Edison invent?\n"
                    "--Is there a device invented by Thomas Edison that produces light?\n"
                    "--What is the name of this device?\n"
                    "-What type of energy powers this device?\n"
                    "--What is energy in this context?\n"
                    "--What is the primary mechanism or process that allows this device to produce light?\n"
                    "--What type of energy drives this mechanism?"
                ),
                3: (
                    "input: What inspired the author of the book \"1984\" to write it?\n"
                    "output:\n"
                    "What inspired the author of the book \"1984\" to write it?\n"
                    "-Who is the author of the book \"1984\"?\n"
                    "--What is the book \"1984\"?\n"
                    "--Who wrote the book \"1984\"?\n"
                    "-What inspired this author to write \"1984\"?\n"
                    "--What was happening during the time this author wrote \"1984\"?\n"
                    "--What personal experiences influenced the author?\n"
                    "--What political or social events might have inspired the author?\n"
                    "--Did any other books or ideas inspire the author?"
                ),
                4: (
                    "input: What is the atomic number of the element discovered in the laboratory where the youngest Nobel Physics laureate worked?\n"
                    "output:\n"
                    "What is the atomic number of the element discovered in the laboratory where the youngest Nobel Physics laureate worked?\n"
                    "-Who is the youngest Nobel Physics laureate?\n"
                    "--When did this person win the Nobel Prize?\n"
                    "--What was their age at the time of the award?\n"
                    "-Where did this laureate work?\n"
                    "--Did this laureate work in laboratory/institution?\n"
                    "--what's the name of the laboratory/institution?\n"
                    "-Was any chemical element discovered at this laboratory?\n"
                    "--What is the name of the element?\n"
                    "--What is its atomic number?"
                ),
                5: (
                    "input: Which country hosted the sporting event where the first female gold medalist in track and field competed?\n"
                    "output:\n"
                    "Which country hosted the sporting event where the first female gold medalist in track and field competed?\n"
                    "-What type of sporting event is being referred to (e.g., Olympics)?\n"
                    "-Who was the first female gold medalist in track and field?\n"
                    "--What is track and field?\n"
                    "--Which female athlete won the first gold medal in this category?\n"
                    "-In which event within track and field did she win?\n"
                    "-Which country hosted this sporting event?"
                ),
            },
            'triples_trans': {
                1: (
                    "input: Triple(s):\n"
                    "(Beijing,located in,China),(Eiffel Tower, located in, Paris),(Apple, founded by, Steve Jobs),"
                    "(Python, created by, Guido van Rossum),(Tesla, CEO of, Elon Musk)\n"
                    "Natural Language Question:\n"
                    "(Beijing,located in,?):Which country does Beijing locate? (?,located in,China):What cities or places are located in China?\n"
                    "(Eiffel Tower, located in, ?):In which city is the Eiffel Tower located? (?, located in, Paris):What landmarks or places are located in Paris?\n"
                    "(Apple, founded by, ?):Who founded Apple? (?, founded by, Steve Jobs):Which companies or organizations were founded by Steve Jobs?\n"
                    "(Python, created by, ?):Who created Python? (?, created by, Guido van Rossum):What programming languages or projects were created by Guido van Rossum?\n"
                    "(Tesla, CEO of, ?):Who is the CEO of Tesla? (?, CEO of, Elon Musk):Which companies or organizations have Elon Musk as their CEO?"
                ),
                2: (
                    "input: Triple(s):\n"
                    "(Shakespeare, wrote, Hamlet),(Titanic, sank in, Atlantic Ocean),(New York City, located in, United States),"
                    "(Harry Potter, written by, J.K. Rowling),(Thomas Edison, invented, Light Bulb),(Amazon River, flows through, Brazil),"
                    "(Mars, known as, Red Planet),(Einstein, won, Nobel Prize),(Venus, closest planet to, Earth),(Cheetah, fastest animal, on land),"
                    "(Pluto, classified as, dwarf planet),(Tokyo, largest city, in Japan),(The Sahara Desert, located in, Africa)\n"
                    "Natural Language Question:\n"
                    "(Shakespeare, wrote, ?):What did Shakespeare write? (?, wrote, Hamlet):Who wrote Hamlet?\n"
                    "(Titanic, sank in, ?):Where did the Titanic sink? (?, sank in, Atlantic Ocean):What sank in the Atlantic Ocean?\n"
                    "(New York City, located in, ?):Where is New York City located? (?, located in, United States):What cities or places are located in the United States?\n"
                    "(Harry Potter, written by, ?):Who wrote Harry Potter? (?, written by, J.K. Rowling):What books or series were written by J.K. Rowling?\n"
                    "(Thomas Edison, invented, ?):What did Thomas Edison invent? (?, invented, Light Bulb):Who invented the light bulb?\n"
                    "(Amazon River, flows through, ?):Through which country does the Amazon River flow? (?, flows through, Brazil):Which rivers flow through Brazil?\n"
                    "(Mars, known as, ?):What is Mars known as? (?, known as, Red Planet):Which celestial bodies are known as the Red Planet?\n"
                    "(Einstein, won, ?):What did Einstein win? (?, won, Nobel Prize):Who won the Nobel Prize?\n"
                    "(Venus, closest planet to, ?):Which planet is closest to Earth? (?, closest planet to, Earth):Which planets are closest to Earth?\n"
                    "(Cheetah, fastest animal, ?):What is the fastest animal? (?, fastest animal, on land):Which animals are the fastest on land?\n"
                    "(Pluto, classified as, ?):How is Pluto classified? (?, classified as, dwarf planet):Which celestial bodies are classified as dwarf planets?\n"
                    "(Tokyo, largest city, ?):Which city is the largest in Japan? (?, largest city, in Japan):Which cities are the largest in Japan?\n"
                    "(The Sahara Desert, located in, ?):Where is The Sahara Desert located? (?, located in, Africa):What deserts or regions are located in Africa?"
                ),
                3: (
                    "input: Triple(s):\n"
                    "(The Great Pyramid of Giza, located in, Egypt),(The Eiffel Tower, built in, 1889),"
                    "(Isaac Newton, discovered, Law of Gravity),(Rome, capital of, Italy),(The Taj Mahal, built by, Shah Jahan),"
                    "(The Moon, orbits around, Earth),(Beethoven, composed, Symphony No. 9),(Tesla, produces, Electric Cars),"
                    "(Galileo, known as, Father of Modern Astronomy),(Nelson Mandela, first president of, South Africa),"
                    "(Mount Kilimanjaro, located in, Tanzania),(Alexander Graham Bell, invented, Telephone)\n"
                    "Natural Language Question:\n"
                    "(The Great Pyramid of Giza, located in, ?):Where is The Great Pyramid of Giza located? (?, located in, Egypt):What landmarks or places are located in Egypt?\n"
                    "(The Eiffel Tower, built in, ?):In which year was The Eiffel Tower built? (?, built in, 1889):What structures were built in 1889?\n"
                    "(Isaac Newton, discovered, ?):What did Isaac Newton discover? (?, discovered, Law of Gravity):Who discovered the Law of Gravity?\n"
                    "(Rome, capital of, ?):What country is Rome the capital of? (?, capital of, Italy):Which cities are the capitals of Italy?\n"
                    "(The Taj Mahal, built by, ?):Who built The Taj Mahal? (?, built by, Shah Jahan):What other structures were built by Shah Jahan?\n"
                    "(The Moon, orbits around, ?):What does The Moon orbit around? (?, orbits around, Earth):Which celestial bodies orbit around Earth?\n"
                    "(Beethoven, composed, ?):What did Beethoven compose? (?, composed, Symphony No. 9):Who composed Symphony No. 9?\n"
                    "(Tesla, produces, ?):What does Tesla produce? (?, produces, Electric Cars):Which products are produced by Tesla?\n"
                    "(Galileo, known as, ?):What is Galileo known as? (?, known as, Father of Modern Astronomy):Which historical figures are known as the Father of Modern Astronomy?\n"
                    "(Nelson Mandela, first president of, ?):Which country was Nelson Mandela the first president of? (?, first president of, South Africa):Who were the first presidents of South Africa?\n"
                    "(Mount Kilimanjaro, located in, ?):Where is Mount Kilimanjaro located? (?, located in, Tanzania):What mountains or regions are located in Tanzania?\n"
                    "(Alexander Graham Bell, invented, ?):What did Alexander Graham Bell invent? (?, invented, Telephone):Who invented the telephone?"
                ),
            },
            'filter_triples': {
                1: (
                    "Input:\n"
                    "user unit queries:\n"
                    "-What is the location that appointed Michelle Bachelet to a governmental position?\n"
                    "--Who is Michelle Bachelet?\n"
                    "--What governmental position was Michelle Bachelet appointed to?\n"
                    "--Where was Michelle Bachelet appointed to this position?\n"
                    "-What language is spoken in this location?\n"
                    "triple unit queries:\n"
                    "(Michelle Bachelet,people.person.nationality,Chile)-What is Michelle Bachelet's nationality?-Which people have Chilean nationality?\n"
                    "(Chile,language.human_language.countries_spoken_in,Spanish Language)-What language is spoken in Chile?-Which countries speak the Spanish Language?\n"
                    "output:\n"
                    "{thought}\n"
                    "step 1:\n"
                    "Let’s first identify the triple unit queries. This will help us find the triple unit queries related to each user unit query later. Below are the triple unit queries:\n"
                    "What is Michelle Bachelet's nationality?-(Michelle Bachelet,people.person.nationality,Chile)\n"
                    "Which people have Chilean nationality?-(Michelle Bachelet,people.person.nationality,Chile)\n"
                    "What language is spoken in Chile?-(Chile,language.human_language.countries_spoken_in,Spanish Language)\n"
                    "Which countries speak the Spanish Language?-(Chile,language.human_language.countries_spoken_in,Spanish Language)\n"
                    "step 2:\n"
                    "Let’s analyze each user unit query and find the related triple unit queries.\n"
                    "For the query \"What is the location that appointed Michelle Bachelet to a governmental position?\",the related query is \"What is Michelle Bachelet's nationality?\",and the corresponding triple is (Michelle Bachelet,people.person.nationality,Chile)\n"
                    "For the query \"Who is Michelle Bachelet?\",the related query is \"What is Michelle Bachelet's nationality?\",and the corresponding triple is (Michelle Bachelet,people.person.nationality,Chile)\n"
                    "For the query \"What governmental position was Michelle Bachelet appointed to?\",the related query is \"What is Michelle Bachelet's nationality?\",and the corresponding triple is (Michelle Bachelet,people.person.nationality,Chile)\n"
                    "For the query \"Where was Michelle Bachelet appointed to this position?\",the related query is \"What is Michelle Bachelet's nationality?\",and the corresponding triple is (Michelle Bachelet,people.person.nationality,Chile)\n"
                    "For the query \"What language is spoken in this location?\",the related query is \"What language is spoken in Chile?\" and \"Which countries speak the Spanish Language?\",and the corresponding triple is (Chile,language.human_language.countries_spoken_in,Spanish Language)\n"
                    "step 3:\n"
                    "In Step 2, we obtained the triple unit queries related to each user unit query, along with their corresponding triples. We will organize them in the output format of triple-user unit queries.\n"
                    "{/thought}\n"
                    "Final output:\n"
                    "What is the location that appointed Michelle Bachelet to a governmental position?-(Michelle Bachelet,people.person.nationality,Chile)\n"
                    "Who is Michelle Bachelet?-(Michelle Bachelet,people.person.nationality,Chile)\n"
                    "What governmental position was Michelle Bachelet appointed to?-(Michelle Bachelet,people.person.nationality,Chile)\n"
                    "Where was Michelle Bachelet appointed to this position?-(Michelle Bachelet,people.person.nationality,Chile)\n"
                    "What language is spoken in this location?-(Chile,language.human_language.countries_spoken_in,Spanish Language)"
                ),
                2: (
                    "Input:\n"
                    "user unit queries:\n"
                    "-What team has Lou Seal as its mascot?\n"
                    "--Who or what is Lou Seal?\n"
                    "--Which team is associated with Lou Seal as its mascot?\n"
                    "-When did this team last win the World Series?\n"
                    "--What is the World Series?\n"
                    "--What year or time frame did this team last win the World Series?\n"
                    "triple unit queries:\n"
                    "(Lou Seal,sports.mascot.team,San Francisco Giants)-Which team has Lou Seal as its mascot?-Who is the mascot of the San Francisco Giants?\n"
                    "(San Francisco Giants,sports.sports_championship_event.champion,2014 World Series)-Which championship event did the San Francisco Giants win?-Which team was the champion of the 2014 World Series?\n"
                    "(San Francisco Giants,sports.sports_team.championships,2012 World Series)-Which championships have the San Francisco Giants won?-Which team won the 2012 World Series?\n"
                    "output:\n"
                    "{thought}\n"
                    "Let’s first identify the triple unit queries. This will help us find the triple unit queries related to each user unit query later. Below are the triple unit queries:\n"
                    "Which team has Lou Seal as its mascot?-(Lou Seal,sports.mascot.team,San Francisco Giants)\n"
                    "Who is the mascot of the San Francisco Giants?-(Lou Seal,sports.mascot.team,San Francisco Giants)\n"
                    "Which championship event did the San Francisco Giants win?-(San Francisco Giants,sports.sports_championship_event.champion,2014 World Series)\n"
                    "Which team was the champion of the 2014 World Series?-(San Francisco Giants,sports.sports_championship_event.champion,2014 World Series)\n"
                    "Which championships have the San Francisco Giants won?-(San Francisco Giants,sports.sports_team.championships,2012 World Series)\n"
                    "Which team won the 2012 World Series?-(San Francisco Giants,sports.sports_team.championships,2012 World Series)\n"
                    "step 2:\n"
                    "Let’s analyze each user unit query and find the related triple unit queries.\n"
                    "For the query \"What team has Lou Seal as its mascot?\",the related query is \"Which team has Lou Seal as its mascot?\",and the corresponding triple is (Lou Seal,sports.mascot.team,San Francisco Giants)\n"
                    "For the query \"Who or what is Lou Seal?\",the related query is None,and the corresponding triple is None\n"
                    "For the query \"Which team is associated with Lou Seal as its mascot?\",the related query is \"Which team has Lou Seal as its mascot?\" and \"Who is the mascot of the San Francisco Giants?\",and the corresponding triple is (Lou Seal,sports.mascot.team,San Francisco Giants)\n"
                    "For the query \"When did this team last win the World Series?\",the related query is \"Which team was the champion of the 2014 World Series?\" and \"Which team won the 2012 World Series?\",and the corresponding triple is (San Francisco Giants,sports.sports_championship_event.champion,2014 World Series) and (San Francisco Giants,sports.sports_team.championships,2012 World Series)\n"
                    "For the query \"What is the World Series?\",the related query is None,and the corresponding triple is None\n"
                    "For the query \"What year or time frame did this team last win the World Series?\",the related query is \"Which team was the champion of the 2014 World Series?\" and \"Which team won the 2012 World Series?\",and the corresponding triple is (San Francisco Giants,sports.sports_championship_event.champion,2014 World Series) and (San Francisco Giants,sports.sports_team.championships,2012 World Series)\n"
                    "step 3:\n"
                    "In Step 2, we obtained the triple unit queries related to each user unit query, along with their corresponding triples. We will organize them in the output format of triple-user unit queries.\n"
                    "{/thought}\n"
                    "Final output:\n"
                    "What team has Lou Seal as its mascot?-(Lou Seal,sports.mascot.team,San Francisco Giants)\n"
                    "Who or what is Lou Seal?-None\n"
                    "Which team is associated with Lou Seal as its mascot?-(Lou Seal,sports.mascot.team,San Francisco Giants)\n"
                    "When did this team last win the World Series?-(San Francisco Giants,sports.sports_championship_event.champion,2014 World Series)-(San Francisco Giants,sports.sports_team.championships,2012 World Series)\n"
                    "What is the World Series?-None\n"
                    "What year or time frame did this team last win the World Series?-(San Francisco Giants,sports.sports_championship_event.champion,2014 World Series)-(San Francisco Giants,sports.sports_team.championships,2012 World Series)"
                ),
                3: (
                    "Input:\n"
                    "user unit queries:\n"
                    "-What is the name of the football sports team?\n"
                    "--Is there a football sports team named Northern Colorado Bears?\n"
                    "--What is the name of this team?\n"
                    "-Is the team located in Greeley, Colorado?\n"
                    "-What educational institution is associated with this football team?\n"
                    "--Does this football team belong to a specific educational institution?\n"
                    "--What is the name of this educational institution?\n"
                    "triple unit queries:\n"
                    "(Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)-Which educational institution has the Northern Colorado Bears football team as one of its sports teams?-Which sports teams belong to the University of Northern Colorado?\n"
                    "(Greeley, location.location.containedby, Greeley Masonic Temple)-What locations or landmarks is Greeley a part of?-Which places or cities are contained by the Greeley Masonic Temple?\n"
                    "(Greeley, location.location.containedby, Bank of Colorado Arena)-What locations or landmarks is Greeley a part of?-Which places or cities are contained by the Bank of Colorado Arena?\n"
                    "(Greeley, location.location.containedby, United States of America)-What locations or landmarks is Greeley a part of?-Which places or cities are located in the United States of America?\n"
                    "(Greeley, location.location.containedby, Jackson Field)-What locations or landmarks is Greeley a part of?-Which places or cities are contained by Jackson Field?\n"
                    "(Greeley, location.location.containedby, Weld County)-What locations or landmarks is Greeley a part of?-Which places or cities are contained by Weld County?\n"
                    "(Greeley, location.location.containedby, Carmike 5)-What locations or landmarks is Greeley a part of?-Which places or cities are contained by Carmike 5?\n"
                    "(Greeley, location.location.containedby, First Baptist Church)-What locations or landmarks is Greeley a part of?-Which places or cities are contained by the First Baptist Church?\n"
                    "(Greeley, location.location.containedby, Colorado)-What locations or landmarks is Greeley a part of?-Which places or cities are located in Colorado?\n"
                    "output:\n"
                    "{thought}\n"
                    "step 1:\n"
                    "Let’s first identify the triple unit queries. This will help us find the triple unit queries related to each user unit query later. Below are the triple unit queries:\n"
                    "Which educational institution has the Northern Colorado Bears football team as one of its sports teams?-(Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "Which sports teams belong to the University of Northern Colorado?-(Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "What locations or landmarks is Greeley a part of?-(Greeley, location.location.containedby, Greeley Masonic Temple)\n"
                    "Which places or cities are contained by the Greeley Masonic Temple?-(Greeley, location.location.containedby, Greeley Masonic Temple)\n"
                    "What locations or landmarks is Greeley a part of?-(Greeley, location.location.containedby, Bank of Colorado Arena)\n"
                    "Which places or cities are contained by the Bank of Colorado Arena?-(Greeley, location.location.containedby, Bank of Colorado Arena)\n"
                    "What locations or landmarks is Greeley a part of?-(Greeley, location.location.containedby, United States of America)\n"
                    "Which places or cities are located in the United States of America?-(Greeley, location.location.containedby, United States of America)\n"
                    "What locations or landmarks is Greeley a part of?-(Greeley, location.location.containedby, Jackson Field)\n"
                    "Which places or cities are contained by Jackson Field?-(Greeley, location.location.containedby, Jackson Field)\n"
                    "What locations or landmarks is Greeley a part of?-(Greeley, location.location.containedby, Weld County)\n"
                    "Which places or cities are contained by Weld County?-(Greeley, location.location.containedby, Weld County)\n"
                    "What locations or landmarks is Greeley a part of?-(Greeley, location.location.containedby, Carmike 5)\n"
                    "Which places or cities are contained by Carmike 5?-(Greeley, location.location.containedby, Carmike 5)\n"
                    "What locations or landmarks is Greeley a part of?-(Greeley, location.location.containedby, First Baptist Church)\n"
                    "Which places or cities are contained by the First Baptist Church?-(Greeley, location.location.containedby, First Baptist Church)\n"
                    "What locations or landmarks is Greeley a part of?-(Greeley, location.location.containedby, Colorado)\n"
                    "Which places or cities are located in Colorado?-(Greeley, location.location.containedby, Colorado)\n"
                    "step 2:\n"
                    "Let’s analyze each user unit query and find the related triple unit queries.\n"
                    "For the query \"What is the name of the football sports team?\",the related query is \"Which educational institution has the Northern Colorado Bears football team as one of its sports teams?\" and \"Which sports teams belong to the University of Northern Colorado?\",and the corresponding triple is (Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "For the query \"Is there a football sports team named Northern Colorado Bears?\",the related query is \"Which educational institution has the Northern Colorado Bears football team as one of its sports teams?\" and \"Which sports teams belong to the University of Northern Colorado?\",and the corresponding triple is (Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "For the query \"What is the name of this team?\",the related query is \"Which educational institution has the Northern Colorado Bears football team as one of its sports teams?\",and the corresponding triple is (Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "For the query \"Is the team located in Greeley, Colorado?\",the related query is \"Which sports teams belong to the University of Northern Colorado?\" and \"What locations or landmarks is Greeley a part of?\" and \"Which places or cities are located in Colorado?\",and the corresponding triple is (Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado) and (Greeley, location.location.containedby, Colorado)\n"
                    "For the query \"What educational institution is associated with this football team?\",the related query is \"Which educational institution has the Northern Colorado Bears football team as one of its sports teams?\" and \"Which sports teams belong to the University of Northern Colorado?\",and the corresponding triple is (Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "For the query \"Does this football team belong to a specific educational institution?\",the related query is \"Which educational institution has the Northern Colorado Bears football team as one of its sports teams?\" and \"Which sports teams belong to the University of Northern Colorado?\",and the corresponding triple is (Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "For the query \"What is the name of this educational institution?\",the related query is \"Which educational institution has the Northern Colorado Bears football team as one of its sports teams?\",and the corresponding triple is (Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "step 3:\n"
                    "In Step 2, we obtained the triple unit queries related to each user unit query, along with their corresponding triples. We will organize them in the output format of triple-user unit queries.\n"
                    "{/thought}\n"
                    "Final output:\n"
                    "What is the name of the football sports team?-(Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "Is there a football sports team named Northern Colorado Bears?-(Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "What is the name of this team?-(Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "Is the team located in Greeley, Colorado?-(Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)-(Greeley, location.location.containedby, Colorado)\n"
                    "What educational institution is associated with this football team?-(Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "Does this football team belong to a specific educational institution?-(Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)\n"
                    "What is the name of this educational institution?-(Northern Colorado Bears football,education.educational_institution.sports_teams,University of Northern Colorado)"
                ),
                4: (
                    "Input:\n"
                    "user unit queries:\n"
                    "-Who is Ovadia Yosef?\n"
                    "--What is Ovadia Yosef known for?\n"
                    "--Did Ovadia Yosef hold a leadership role in a religion?\n"
                    "-What religion is associated with Ovadia Yosef?\n"
                    "--Is there a predominant religion associated with Ovadia Yosef?\n"
                    "--What is the name of this religion?\n"
                    "triple unit queries:\n"
                    "(Ovadia Yosef, people.person.religion, Judaism)-What religion is Ovadia Yosef associated with?-Who is associated with Judaism?\n"
                    "(Ovadia Yosef, people.person.religion, Haredi Judaism)-Who is associated with Haredi Judaism?\n"
                    "(Ovadia Yosef, people.person.nationality, Israel)-What is Ovadia Yosef's nationality?-Who has Israel as their nationality?\n"
                    "(Israel, location.location.containedby, Tiberias)-What locations or landmarks are contained within Israel?-Which countries or regions contain Tiberias?\n"
                    "(Israel, location.location.containedby, Northern District)-Which countries or regions contain the Northern District?\n"
                    "(Israel, location.location.containedby, Atarot Airport)-Which countries or regions contain Atarot Airport?\n"
                    "(Israel, location.location.containedby, Tel Aviv District)-Which countries or regions contain the Tel Aviv District?\n"
                    "(Israel, location.location.containedby, Safed)-Which countries or regions contain Safed?\n"
                    "(Israel, location.location.containedby, Dome of the Rock)-Which countries or regions contain the Dome of the Rock?\n"
                    "(Israel, location.location.containedby, Har HaMenuchot)-Which countries or regions contain Har HaMenuchot?\n"
                    "(Israel, location.location.containedby, Church of the Holy Sepulchre)-Which countries or regions contain the Church of the Holy Sepulchre?\n"
                    "(Israel, location.location.containedby, Porat Yosef Yeshiva)-Which countries or regions contain Porat Yosef Yeshiva?\n"
                    "(Israel, location.location.containedby, Mount Herzl)-Which countries or regions contain Mount Herzl?\n"
                    "output:\n"
                    "{thought}\n"
                    "step 1:\n"
                    "Let’s first identify the triple unit queries. This will help us find the triple unit queries related to each user unit query later. Below are the triple unit queries:\n"
                    "What religion is Ovadia Yosef associated with?-(Ovadia Yosef, people.person.religion, Judaism)\n"
                    "Who is associated with Judaism?-(Ovadia Yosef, people.person.religion, Judaism)\n"
                    "Who is associated with Haredi Judaism?-(Ovadia Yosef, people.person.religion, Haredi Judaism)\n"
                    "What is Ovadia Yosef's nationality?-(Ovadia Yosef, people.person.nationality, Israel)\n"
                    "Who has Israel as their nationality?-(Ovadia Yosef, people.person.nationality, Israel)\n"
                    "What locations or landmarks are contained within Israel?-(Israel, location.location.containedby, Tiberias)\n"
                    "Which countries or regions contain Tiberias?-(Israel, location.location.containedby, Tiberias)\n"
                    "Which countries or regions contain the Northern District?-(Israel, location.location.containedby, Northern District)\n"
                    "Which countries or regions contain Atarot Airport?-(Israel, location.location.containedby, Atarot Airport)\n"
                    "Which countries or regions contain the Tel Aviv District?-(Israel, location.location.containedby, Tel Aviv District)\n"
                    "Which countries or regions contain Safed?-(Israel, location.location.containedby, Safed)\n"
                    "Which countries or regions contain the Dome of the Rock?-(Israel, location.location.containedby, Dome of the Rock)\n"
                    "Which countries or regions contain Har HaMenuchot?-(Israel, location.location.containedby, Har HaMenuchot)\n"
                    "Which countries or regions contain the Church of the Holy Sepulchre?-(Israel, location.location.containedby, Church of the Holy Sepulchre)\n"
                    "Which countries or regions contain Porat Yosef Yeshiva?-(Israel, location.location.containedby, Porat Yosef Yeshiva)\n"
                    "Which countries or regions contain Mount Herzl?-(Israel, location.location.containedby, Mount Herzl)\n"
                    "step 2:\n"
                    "Let’s analyze each user unit query and find the related triple unit queries.\n"
                    "For the query \"Who is Ovadia Yosef?\",the related query is \"What religion is Ovadia Yosef associated with?\" and \"What is Ovadia Yosef's nationality?\",and the corresponding triple is (Ovadia Yosef, people.person.religion, Judaism) and (Ovadia Yosef, people.person.nationality, Israel)\n"
                    "For the query \"What is Ovadia Yosef known for?\",the related query is None,and the corresponding triple is None\n"
                    "For the query \"Did Ovadia Yosef hold a leadership role in a religion?\",the related query is \"What religion is Ovadia Yosef associated with?\" and \"What is Ovadia Yosef's nationality\",and the corresponding triple is (Ovadia Yosef, people.person.religion, Judaism)\n"
                    "For the query \"What religion is associated with Ovadia Yosef?\",the related query is \"What religion is Ovadia Yosef associated with?\",and the corresponding triple is (Ovadia Yosef, people.person.religion, Judaism)\n"
                    "For the query \"Is there a predominant religion associated with Ovadia Yosef?\",the related query is \"What religion is Ovadia Yosef associated with?\",and the corresponding triple is (Ovadia Yosef, people.person.religion, Judaism)\n"
                    "For the query \"What is the name of this religion?\",the related query is \"What religion is Ovadia Yosef associated with?\",and the corresponding triple is (Ovadia Yosef, people.person.religion, Judaism)\n"
                    "step 3:\n"
                    "In Step 2, we obtained the triple unit queries related to each user unit query, along with their corresponding triples. We will organize them in the output format of triple-user unit queries.\n"
                    "{/thought}\n"
                    "Final output:\n"
                    "Who is Ovadia Yosef?-(Ovadia Yosef, people.person.religion, Judaism)-(Ovadia Yosef, people.person.nationality, Israel)\n"
                    "What is Ovadia Yosef known for?-None\n"
                    "Did Ovadia Yosef hold a leadership role in a religion?-(Ovadia Yosef, people.person.religion, Judaism)\n"
                    "What religion is associated with Ovadia Yosef?-(Ovadia Yosef, people.person.religion, Judaism)\n"
                    "Is there a predominant religion associated with Ovadia Yosef?-(Ovadia Yosef, people.person.religion, Judaism)\n"
                    "What is the name of this religion?-(Ovadia Yosef, people.person.religion, Judaism)"
                ),
                5: (
                    "Input:\n"
                    "user unit queries:\n"
                    "-Who was the champion of the 1931 World Series Championship?\n"
                    "--What is the World Series Championship?\n"
                    "--Who won the World Series in 1931?\n"
                    "-Where does this champion team play?\n"
                    "--What is the name of the stadium associated with this team?\n"
                    "--Was this stadium their home stadium in 1931?\n"
                    "triple unit queries:\n"
                    "(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)-Which team won the 1931 World Series?-Which championships were won by the St. Louis Cardinals?\n"
                    "(St. Louis Cardinals, sports.sports_team.arena_stadium, Busch Stadium)-What stadiums or arenas are associated with the St. Louis Cardinals?-Which teams play at Busch Stadium?\n"
                    "(St. Louis Cardinals, sports.sports_team.arena_stadium, Roger Dean Stadium)-Which teams play at Roger Dean Stadium?-What is the home ground of the St. Louis Cardinals?\n"
                    "(St. Louis Cardinals, home ground of, Busch Stadium)-Which teams have Busch Stadium as their home ground?\n"
                    "(St. Louis Cardinals, home ground of, Roger Dean Stadium)-Which teams have Roger Dean Stadium as their home ground?\n"
                    "(St. Louis Cardinals, plays at, Busch Stadium)-Where does the St. Louis Cardinals play?-Which teams play at Busch Stadium?\n"
                    "(St. Louis Cardinals, plays at, Roger Dean Stadium)-Which teams play at Roger Dean Stadium?\n"
                    "(St. Louis Cardinals, has arena, Busch Stadium)-What arenas or stadiums are associated with the St. Louis Cardinals?-Which teams are associated with Busch Stadium?\n"
                    "(St. Louis Cardinals, has arena, Roger Dean Stadium)-Which teams are associated with Roger Dean Stadium?\n"
                    "output:\n"
                    "{thought}\n"
                    "step 1:\n"
                    "Let’s first identify the triple unit queries. This will help us find the triple unit queries related to each user unit query later. Below are the triple unit queries:\n"
                    "Which team won the 1931 World Series?-(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)\n"
                    "Which championships were won by the St. Louis Cardinals?-(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)\n"
                    "What stadiums or arenas are associated with the St. Louis Cardinals?-(St. Louis Cardinals, sports.sports_team.arena_stadium, Busch Stadium)\n"
                    "Which teams play at Busch Stadium?-(St. Louis Cardinals, sports.sports_team.arena_stadium, Busch Stadium)\n"
                    "Which teams play at Roger Dean Stadium?-(St. Louis Cardinals, sports.sports_team.arena_stadium, Roger Dean Stadium)\n"
                    "What is the home ground of the St. Louis Cardinals?-(St. Louis Cardinals, sports.sports_team.arena_stadium, Roger Dean Stadium)\n"
                    "Which teams have Busch Stadium as their home ground?-(St. Louis Cardinals, home ground of, Busch Stadium)\n"
                    "Which teams have Roger Dean Stadium as their home ground?-(St. Louis Cardinals, home ground of, Roger Dean Stadium)\n"
                    "Where does the St. Louis Cardinals play?-(St. Louis Cardinals, plays at, Busch Stadium)\n"
                    "Which teams play at Busch Stadium?-(St. Louis Cardinals, plays at, Busch Stadium)\n"
                    "Which teams play at Roger Dean Stadium?-(St. Louis Cardinals, plays at, Roger Dean Stadium)\n"
                    "What arenas or stadiums are associated with the St. Louis Cardinals?-(St. Louis Cardinals, has arena, Busch Stadium)\n"
                    "Which teams are associated with Busch Stadium?-(St. Louis Cardinals, has arena, Busch Stadium)\n"
                    "Which teams are associated with Roger Dean Stadium?-(St. Louis Cardinals, has arena, Roger Dean Stadium)\n"
                    "step 2:\n"
                    "Let’s analyze each user unit query and find the related triple unit queries.\n"
                    "For the query \"Who was the champion of the 1931 World Series Championship?\",the related query is \"Which team won the 1931 World Series?\",and the corresponding triple is (1931 World Series, sports.sports_team.championships, St. Louis Cardinals)\n"
                    "For the query \"What is the World Series Championship?\",the related query is None,and the corresponding triple is None\n"
                    "For the query \"Who won the World Series in 1931?\",the related query is \"Which team won the 1931 World Series?\",and the corresponding triple is (1931 World Series, sports.sports_team.championships, St. Louis Cardinals)\n"
                    "For the query \"Where does this champion team play?\",the related query is \"Where does the St. Louis Cardinals play?\" and \"What stadiums or arenas are associated with the St. Louis Cardinals?\",and the corresponding triple is (St. Louis Cardinals, plays at, Busch Stadium) and (St. Louis Cardinals, has arena, Busch Stadium)\n"
                    "For the query \"What is the name of the stadium associated with this team?\",the related query is \"What stadiums or arenas are associated with the St. Louis Cardinals?\" and \"What arenas or stadiums are associated with the St. Louis Cardinals?\",and the corresponding triple is (St. Louis Cardinals, sports.sports_team.arena_stadium, Busch Stadium) and (St. Louis Cardinals, has arena, Busch Stadium)\n"
                    "For the query \"Was this stadium their home stadium in 1931?\",the related query is \"What is the home ground of the St. Louis Cardinals?\" and \"Which teams have Busch Stadium as their home ground?\" and \"Which teams have Roger Dean Stadium as their home ground?\",and the corresponding triple is (St. Louis Cardinals, sports.sports_team.arena_stadium, Roger Dean Stadium) and (St. Louis Cardinals, home ground of, Busch Stadium) and (St. Louis Cardinals, home ground of, Roger Dean Stadium)\n"
                    "step 3:\n"
                    "In Step 2, we obtained the triple unit queries related to each user unit query, along with their corresponding triples. We will organize them in the output format of triple-user unit queries.\n"
                    "{/thought}\n"
                    "Final output:\n"
                    "Who was the champion of the 1931 World Series Championship?-(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)\n"
                    "What is the World Series Championship?-None\n"
                    "Who won the World Series in 1931?-(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)\n"
                    "Where does this champion team play?-(St. Louis Cardinals, plays at, Busch Stadium)-(St. Louis Cardinals, has arena, Busch Stadium)\n"
                    "What is the name of the stadium associated with this team?-(St. Louis Cardinals, sports.sports_team.arena_stadium, Busch Stadium)-(St. Louis Cardinals, has arena, Busch Stadium)\n"
                    "Was this stadium their home stadium in 1931?-(St. Louis Cardinals, sports.sports_team.arena_stadium, Roger Dean Stadium)-(St. Louis Cardinals, home ground of, Busch Stadium)-(St. Louis Cardinals, home ground of, Roger Dean Stadium)"
                )
            },
            'filter_entities': {
                
            },'structral_enrich': {
                1: (
                    "Input:\n"
                    "(Michelle Bachelet,people.person.nationality,Chile)-What is the location that appointed Michelle Bachelet to a governmental position?-Who is Michelle Bachelet?-What governmental position was Michelle Bachelet appointed to?-Where was Michelle Bachelet appointed to this position?\n"
                    "(Chile,language.human_language.countries_spoken_in,Spanish Language)-What language is spoken in this location?\n"
                    "1-hop:\n"
                    "(Michelle Bachelet,people.person.nationality,Chile)\n"
                    "2-hop:\n"
                    "(Michelle Bachelet,people.person.nationality,Chile)->(Chile,language.human_language.countries_spoken_in,Spanish Language)\n"
                    "Output:\n"
                    "{thought}\n"
                    "step 1:\n"
                    "To prepare for the subsequent semantic enhancement of the triples and bridge the semantic gap between the triples and the user queries, let me review the triples along with their corresponding user query(ies):\n"
                    "(Michelle Bachelet,people.person.nationality,Chile)-What is the location that appointed Michelle Bachelet to a governmental position?-Who is Michelle Bachelet?-What governmental position was Michelle Bachelet appointed to?-Where was Michelle Bachelet appointed to this position?\n"
                    "(Chile,language.human_language.countries_spoken_in,Spanish Language)-What language is spoken in this location?\n"
                    "step 2:\n"
                    "Using the similarity property, perform semantic enhancement on the given 1-hop subgraph:\n"
                    "For the 1-hop subgraph (Michelle Bachelet,people.person.nationality,Chile),the related queries are \"What is the location that appointed Michelle Bachelet to a governmental position?\" , \"Who is Michelle Bachelet?\" , \"What governmental position was Michelle Bachelet appointed to?\" , \"Where was Michelle Bachelet appointed to this position?\" .Combining these queries, The newly added  triple(s) is/are (Michelle Bachelet,appointed_government_position_in,Chile)\n"
                    "Using the symmetry properties, perform semantic enhancement on the given 1-hop subgraph:\n"
                    "For the 1-hop subgraph (Michelle Bachelet,people.person.nationality,Chile),the related queries are \"What is the location that appointed Michelle Bachelet to a governmental position?\" , \"Who is Michelle Bachelet?\" , \"What governmental position was Michelle Bachelet appointed to?\" , \"Where was Michelle Bachelet appointed to this position?\" .Combining these queries, The newly added  triple(s) is/are (Chile, appointed_as_government_official_by, Michelle Bachelet)\n"
                    "step 3:\n"
                    "Using the transitivity properties, perform semantic enhancement on the given 2-hop subgraph:\n"
                    "For the 2-hop subgraph (Michelle Bachelet,people.person.nationality,Chile)->(Chile,language.human_language.countries_spoken_in,Spanish Language),the related queries are \"What is the location that appointed Michelle Bachelet to a governmental position?\" , \"Who is Michelle Bachelet?\" , \"What governmental position was Michelle Bachelet appointed to?\" , \"Where was Michelle Bachelet appointed to this position?\" , What language is spoken in this location?. Combining these queries, The newly added  triple(s) is/are (Michelle Bachelet, language_of_the_country_where_appointed ,Spanish Language)\n"
                    "{/thought}\n"
                    "step 4:\n"
                    "(Michelle Bachelet,appointed_government_position_in,Chile)\n"
                    "(Chile, appointed_as_government_official_by, Michelle Bachelet)\n"
                    "(Michelle Bachelet, language_of_the_country_where_appointed ,Spanish Language)\n"
                ),
                2: (
                    "Input:\n"
                    "(Lou Seal,sports.mascot.team,San Francisco Giants)-What team has Lou Seal as its mascot?-Which team is associated with Lou Seal as its mascot?\n"
                    "(San Francisco Giants,sports.sports_championship_event.champion,2014 World Series)-When did this team last win the World Series?-What year or time frame did this team last win the World Series?\n"
                    "(San Francisco Giants,sports.sports_team.championships,2012 World Series)-When did this team last win the World Series?-What year or time frame did this team last win the World Series?\n"
                    "1-hop:\n"
                    "(Lou Seal,sports.mascot.team,San Francisco Giants)\n"
                    "2-hop:\n"
                    "(Lou Seal,sports.mascot.team,San Francisco Giants)->(San Francisco Giants,sports.sports_championship_event.champion,2014 World Series)\n"
                    "(Lou Seal,sports.mascot.team,San Francisco Giants)->(San Francisco Giants,sports.sports_team.championships,2012 World Series)\n"
                    "Output:\n"
                    "{thought}\n"
                    "step 1:\n"
                    "To prepare for the subsequent semantic enhancement of the triples and bridge the semantic gap between the triples and the user queries, let me review the triples along with their corresponding user query(ies):\n"
                    "(Lou Seal,sports.mascot.team,San Francisco Giants)-What team has Lou Seal as its mascot?-Which team is associated with Lou Seal as its mascot?\n"
                    "(San Francisco Giants,sports.sports_championship_event.champion,2014 World Series)-When did this team last win the World Series?-What year or time frame did this team last win the World Series?\n"
                    "(San Francisco Giants,sports.sports_team.championships,2012 World Series)-When did this team last win the World Series?-What year or time frame did this team last win the World Series?\n"
                    "step 2:\n"
                    "Using the similarity property, perform semantic enhancement on the given 1-hop subgraph:\n"
                    "For the 1-hop subgraph (Lou Seal,sports.mascot.team,San Francisco Giants),the related queries are \"What team has Lou Seal as its mascot?\" , \"Which team is associated with Lou Seal as its mascot?\" . Combining these queries, The newly added  triple(s) is/are (Lou Seal,associated_with_team,San Francisco Giants)\n"
                    "Using the symmetry properties, perform semantic enhancement on the given 1-hop subgraph:\n"
                    "For the 1-hop subgraph (Lou Seal,sports.mascot.team,San Francisco Giants),the related queries are \"What team has Lou Seal as its mascot?\" , \"Which team is associated with Lou Seal as its mascot?\" . Combining these queries, The newly added  triple(s) is/are (San Francisco Giants,has_mascot,Lou Seal)\n"
                    "step 3:\n"
                    "Using the transitivity properties, perform semantic enhancement on the given 2-hop subgraph:\n"
                    "For the 2-hop subgraph (Lou Seal,sports.mascot.team,San Francisco Giants)->(San Francisco Giants,sports.sports_championship_event.champion,2014 World Series),the related queries are \"What team has Lou Seal as its mascot?\" and \"Which team is associated with Lou Seal as its mascot?\" , \"When did this team last win the World Series?\" , \"What year or time frame did this team last win the World Series?\" . Combining these queries, The newly added  triple(s) is/are (Lou Seal,mascot_of_team_that_last_won,2014 World Series)\n"
                    "For the 2-hop subgraph (Lou Seal,sports.mascot.team,San Francisco Giants)->(San Francisco Giants,sports.sports_team.championships,2012 World Series),the related queries are \"What team has Lou Seal as its mascot?\" and \"Which team is associated with Lou Seal as its mascot?\" , \"When did this team last win the World Series?\" , \"What year or time frame did this team last win the World Series?\" . Combining these queries, The newly added  triple(s) is/are (Lou Seal,mascot_of_team_that_won,2012 World Series)\n"
                    "{/thought}\n"
                    "step 4:\n"
                    "(Lou Seal,associated_with_team,San Francisco Giants)\n"
                    "(San Francisco Giants,has_mascot,Lou Seal)\n"
                    "(Lou Seal,mascot_of_team_that_last_won,2014 World Series)\n"
                    "(Lou Seal,mascot_of_team_that_won,2012 World Series)\n"
                ),
                3: (
                    "Input:\n"
                    "(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)-Who was the champion of the 1931 World Series Championship?-Who won the World Series in 1931?\n"
                    "(St. Louis Cardinals, plays at, Busch Stadium)-Where does this champion team play?\n"
                    "(St. Louis Cardinals, has arena, Busch Stadium)-Where does this champion team play?-What is the name of the stadium associated with this team?\n"
                    "(St. Louis Cardinals, sports.sports_team.arena_stadium, Busch Stadium)-What is the name of the stadium associated with this team?\n"
                    "(St. Louis Cardinals, sports.sports_team.arena_stadium, Roger Dean Stadium)-Was this stadium their home stadium in 1931?\n"
                    "(St. Louis Cardinals, home ground of, Busch Stadium)-Was this stadium their home stadium in 1931?\n"
                    "(St. Louis Cardinals, home ground of, Roger Dean Stadium)-Was this stadium their home stadium in 1931?\n"
                    "1-hop:\n"
                    "(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)\n"
                    "2-hop:\n"
                    "(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, plays at, Busch Stadium)\n"
                    "(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, has arena, Busch Stadium)\n"
                    "(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, sports.sports_team.arena_stadium, Busch Stadium)\n"
                    "(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, sports.sports_team.arena_stadium, Roger Dean Stadium)\n"
                    "(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, home ground of, Busch Stadium)\n"
                    "(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, home ground of, Roger Dean Stadium)\n"
                    "Output:\n"
                    "{thought}\n"
                    "step 1:\n"
                    "To prepare for the subsequent semantic enhancement of the triples and bridge the semantic gap between the triples and the user queries, let me review the triples along with their corresponding user query(ies):\n"
                    "(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)-Who was the champion of the 1931 World Series Championship?-Who won the World Series in 1931?\n"
                    "(St. Louis Cardinals, plays at, Busch Stadium)-Where does this champion team play?\n"
                    "(St. Louis Cardinals, has arena, Busch Stadium)-Where does this champion team play?-What is the name of the stadium associated with this team?\n"
                    "(St. Louis Cardinals, sports.sports_team.arena_stadium, Busch Stadium)-What is the name of the stadium associated with this team?\n"
                    "(St. Louis Cardinals, sports.sports_team.arena_stadium, Roger Dean Stadium)-Was this stadium their home stadium in 1931?\n"
                    "(St. Louis Cardinals, home ground of, Busch Stadium)-Was this stadium their home stadium in 1931?\n"
                    "(St. Louis Cardinals, home ground of, Roger Dean Stadium)-Was this stadium their home stadium in 1931?\n"
                    "step 2:\n"
                    "Using the similarity property, perform semantic enhancement on the given 1-hop subgraph:\n"
                    "For the 1-hop subgraph (1931 World Series, sports.sports_team.championships, St. Louis Cardinals),the related queries are \"Who was the champion of the 1931 World Series Championship?\" and \"Who won the World Series in 1931?\".Combining these queries, The newly added  triple(s) is/are (1931 World Series, champion_1931_World_Series, St. Louis Cardinals)\n"
                    "Using the symmetry properties, perform semantic enhancement on the given 1-hop subgraph:\n"
                    "For the 1-hop subgraph (1931 World Series, sports.sports_team.championships, St. Louis Cardinals),the related queries are \"Who was the champion of the 1931 World Series Championship?\" and \"Who won the World Series in 1931?\".Combining these queries, The newly added  triple(s) is/are (St. Louis Cardinals, won_1931_World_Series_as_champion, 1931 World Series)\n"
                    "step 3:\n"
                    "Using the transitivity properties, perform semantic enhancement on the given 2-hop subgraph:\n"
                    "For the 2-hop subgraph (1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, plays at, Busch Stadium),the related queries are \"Who was the champion of the 1931 World Series Championship?\" and \"Who won the World Series in 1931?\" and \"Where does this champion team play?\".Combining these queries, The newly added triple(s) is/are (1931 World Series, champion_team_plays_at, Busch Stadium)\n"
                    "For the 2-hop subgraph (1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, has arena, Busch Stadium),the related queries are \"Who was the champion of the 1931 World Series Championship?\" and \"Who won the World Series in 1931?\" and \"Where does this champion team play?\" and \"What is the name of the stadium associated with this team?\".Combining these queries, The newly added triple(s) is/are (1931 World Series, stadium_related_to_champion_team, Busch Stadium)\n"
                    "For the 2-hop subgraph (1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, sports.sports_team.arena_stadium, Busch Stadium),the related queries are \"Who was the champion of the 1931 World Series Championship?\" and \"Who won the World Series in 1931?\" and \"What is the name of the stadium associated with this team?\".Combining these queries, The newly added triple(s) is/are (1931 World Series, stadium_related_to_champion_team, Busch Stadium)\n"
                    "For the 2-hop subgraph (1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, sports.sports_team.arena_stadium, Roger Dean Stadium),the related queries are \"Who was the champion of the 1931 World Series Championship?\" and \"Who won the World Series in 1931?\" and \"Was this stadium their home stadium in 1931?\".Combining these queries, The newly added triple(s) is/are (1931 World Series, home_stadium_related_to_champion_team, Roger Dean Stadium)\n"
                    "For the 2-hop subgraph (1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, home ground of, Busch Stadium),the related queries are \"Who was the champion of the 1931 World Series Championship?\" and \"Who won the World Series in 1931?" and "Was this stadium their home stadium in 1931?\".Combining these queries, The newly added triple(s) is/are (1931 World Series, home_stadium_related_to_champion_team, Busch Stadium)\n"
                    "For the 2-hop subgraph (1931 World Series, sports.sports_team.championships, St. Louis Cardinals)->(St. Louis Cardinals, home ground of, Roger Dean Stadium),the related queries are \"Who was the champion of the 1931 World Series Championship?\" and \"Who won the World Series in 1931?" and "Was this stadium their home stadium in 1931?\".Combining these queries, The newly added triple(s) is/are (1931 World Series, home_stadium_related_to_champion_team, Roger Dean Stadium)\n"
                    "{/thought}\n"
                    "step 4:\n"
                    "(1931 World Series, champion_1931_World_Series, St. Louis Cardinals)\n"
                    "(St. Louis Cardinals, won_1931_World_Series_as_champion, 1931 World Series)\n"
                    "(1931 World Series, champion_team_plays_at, Busch Stadium)\n"
                    "(1931 World Series, stadium_related_to_champion_team, Busch Stadium)\n"
                    "(1931 World Series, home_stadium_related_to_champion_team, Roger Dean Stadium)\n"
                    "(1931 World Series, home_stadium_related_to_champion_team, Busch Stadium)\n"
                )
            },'feature_enrich': {
                1: (
                    "Input:\n"
                    "entity List:\n"
                    "[$Michelle Bachelet$ context]\n"
                    "relavent triple(s):(Michelle Bachelet,people.person.nationality,Chile)\n"
                    "relavent user query(ies) is the location that appointed Michelle Bachelet to a governmental position?-Who is Michelle Bachelet?-What governmental position was Michelle Bachelet appointed to?-Where was Michelle Bachelet appointed to this position?\n"
                    "[/$Michelle Bachelet$ context]\n"
                    "[$Chile$ context]\n"
                    "relavent triple(s):(Michelle Bachelet,people.person.nationality,Chile)-(Chile,language.human_language.countries_spoken_in,Spanish Language)\n"
                    "relavent user query(ies) is the location that appointed Michelle Bachelet to a governmental position?-Who is Michelle Bachelet?-What governmental position was Michelle Bachelet appointed to?-Where was Michelle Bachelet appointed to this position?-What language is spoken in this location?\n"
                    "[/$Chile$ context]\n"
                    "Output:\n"
                    "{result}\n"
                    "(Michelle Bachelet, Hypernym_isA, Political Figure)\n"
                    "(Michelle Bachelet, Hypernym_isA, President)\n"
                    "(Chile, Hypernym_isA, Country)\n"
                    "(Chile, Hypernym_locateAt, South America)\n"
                    "(Chile, Inclusion_hasContext, Spanish Language)\n"
                    "{/result}\n"
                ),
                2: (
                    "Input:\n"
                    "entity List:\n"
                    "[$Ovadia Yosef$ context]\n"
                    "relavent triple(s):(Ovadia Yosef, people.person.religion, Judaism)-(Ovadia Yosef, people.person.nationality, Israel)\n"
                    "relavent user query(ies) is Ovadia Yosef?-Did Ovadia Yosef hold a leadership role in a religion?-What religion is associated with Ovadia Yosef?-Is there a predominant religion associated with Ovadia Yosef?-What is the name of this religion?\n"
                    "[/$Ovadia Yosef$ context]\n"
                    "[$Judaism$ context]\n"
                    "relavent triple(s):(Ovadia Yosef, people.person.religion, Judaism)\n"
                    "relavent user query(ies) is Ovadia Yosef?-Did Ovadia Yosef hold a leadership role in a religion?-What religion is associated with Ovadia Yosef?-Is there a predominant religion associated with Ovadia Yosef?-What is the name of this religion?\n"
                    "[/$Judaism$ context]\n"
                    "[$Israel$ context]\n"
                    "relavent triple(s):(Ovadia Yosef, people.person.nationality, Israel)\n"
                    "relavent user query(ies) is Ovadia Yosef?\n"
                    "[/$Israel$ context]\n"
                    "Output:\n"
                    "{result}\n"
                    "(Ovadia Yosef, Hypernym_isA, Religious Leader)\n"
                    "(Ovadia Yosef, Induction_belongTo, Jewish Religious Leaders)\n"
                    "(Judaism, Hypernym_isA, Religion)\n"
                    "(Judaism, Inclusion_hasContext, Jewish Culture)\n"
                    "(Israel, Hypernym_isA, Country)\n"
                    "(Israel, Hypernym_locateAt, Middle East)\n"
                    "{/result}\n"
                ),
                3: (
                    "Input:\n"
                    "entity List:\n"
                    "[$1931 World Series$ context]\n"
                    "relavent triple(s):(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)\n"
                    "relavent user query(ies) was the champion of the 1931 World Series Championship?-Who won the World Series in 1931?\n"
                    "[/$1931 World Series$ context]\n"
                    "[$St. Louis Cardinals$ context]\n"
                    "relavent triple(s):(1931 World Series, sports.sports_team.championships, St. Louis Cardinals)-(St. Louis Cardinals, plays at, Busch Stadium)-(St. Louis Cardinals, has arena, Busch Stadium)-(St. Louis Cardinals, sports.sports_team.arena_stadium, Busch Stadium)-(St. Louis Cardinals, sports.sports_team.arena_stadium, Roger Dean Stadium)-(St. Louis Cardinals, home ground of, Busch Stadium)-(St. Louis Cardinals, home ground of, Roger Dean Stadium)\n"
                    "relavent user query(ies) was the champion of the 1931 World Series Championship?-Who won the World Series in 1931?-Where does this champion team play?-Where does this champion team play?-What is the name of the stadium associated with this team?-What is the name of the stadium associated with this team?-Was this stadium their home stadium in 1931?-Was this stadium their home stadium in 1931?-Was this stadium their home stadium in 1931?\n"
                    "[/$St. Louis Cardinals$ context]\n"
                    "[$Busch Stadium$ context]\n"
                    "relavent triple(s):(St. Louis Cardinals, plays at, Busch Stadium)-(St. Louis Cardinals, has arena, Busch Stadium)-(St. Louis Cardinals, sports.sports_team.arena_stadium, Busch Stadium)-(St. Louis Cardinals, home ground of, Busch Stadium)\n"
                    "relavent user query(ies) does this champion team play?-Where does this champion team play?-What is the name of the stadium associated with this team?-Was this stadium their home stadium in 1931?\n"
                    "[/$Busch Stadium$ context]\n"
                    "[$Roger Dean Stadium$ context]\n"
                    "relavent triple(s):(St. Louis Cardinals, sports.sports_team.arena_stadium, Roger Dean Stadium)-(St. Louis Cardinals, home ground of, Roger Dean Stadium)\n"
                    "relavent user query(ies) this stadium their home stadium in 1931?-Was this stadium their home stadium in 1931?\n"
                    "[/$Roger Dean Stadium$ context]\n"
                    "Output:\n"
                    "{result}\n"
                    "(1931 World Series, Hypernym_isA, Sports Championship)\n"
                    "(1931 World Series, Induction_belongTo, Baseball Championships)\n"
                    "(St. Louis Cardinals, Hypernym_isA, Baseball Team)\n"
                    "(St. Louis Cardinals, Hypernym_locateAt, United States)\n"
                    "(St. Louis Cardinals, Inclusion_isPartOf, Major League Baseball)\n"
                    "(Busch Stadium, Hypernym_isA, Sports Arena)\n"
                    "(Busch Stadium, Induction_belongTo, Baseball Stadiums)\n"
                    "(Roger Dean Stadium, Hypernym_isA, Sports Arena)\n"
                    "(Roger Dean Stadium, Induction_belongTo, Baseball Stadiums)\n"
                    "{/result}\n"
                )
            },'qa': {

            },'direct_qa': {

            }
        }
        # 根据当前模式获取示例
        examples = demonstrations_dict.get(self.mode, {})
        if not examples:
            return "No demonstrations available."
        # 动态组装 {demonstrations}{/demonstrations} 
        demonstrations = ""
        for example_id, example_content in examples.items():
            demonstrations += f"### Example {example_id}:\n{example_content}\n\n"
        # 移除末尾多余的换行符\n
        return demonstrations.strip()
        

    def build_prompt(self):
        """
        组装最终的 prompt。
        """
        prompt = (
            "[INST] <<SYS>>\n"
            f"{self.role}\n"
            "<</SYS>>\n"
            f"{{instruction}}\n{self.instruction}\n{{/instruction}}\n"
            f"{{demonstrations}}\n{self.demonstrations}\n{{/demonstrations}}\n"
            "### Your Turn\n"
            f"Input:\n {self.question}\n"
            "[/INST]"
        )
        return prompt